# flake8: noqa
# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_rtdc_file = QtGui.QAction(parent=MainWindow)
        self.actionOpen_rtdc_file.setObjectName("actionOpen_rtdc_file")
        self.actionSegmentRrtdcFile = QtGui.QAction(parent=MainWindow)
        self.actionSegmentRrtdcFile.setObjectName("actionSegmentRrtdcFile")
        self.actionSegmentPngImages = QtGui.QAction(parent=MainWindow)
        self.actionSegmentPngImages.setObjectName("actionSegmentPngImages")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionExportImages = QtGui.QAction(parent=MainWindow)
        self.actionExportImages.setObjectName("actionExportImages")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSoftware = QtGui.QAction(parent=MainWindow)
        self.actionSoftware.setObjectName("actionSoftware")
        self.actionDocumentation = QtGui.QAction(parent=MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuFile.addAction(self.actionSegmentRrtdcFile)
        self.menuFile.addAction(self.actionSegmentPngImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionSoftware)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_rtdc_file.setText(_translate("MainWindow", "Start/continue segmenting an .rtdc file..."))
        self.actionSegmentRrtdcFile.setText(_translate("MainWindow", "Segment .&rtdc file..."))
        self.actionSegmentPngImages.setText(_translate("MainWindow", "Segment .&png images..."))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionExportImages.setText(_translate("MainWindow", "&Export images..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSoftware.setText(_translate("MainWindow", "Software"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
